import { describe, it, expect } from 'vitest';
import { extractYouTubeId, parseISODuration, shouldShowCustomPip } from './media';

describe('Media Utility - YouTube ID Extraction', () => {
  it('should extract the correct video ID from a standard YouTube watch URL', () => {
    const url = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ';
    const result = extractYouTubeId(url);
    expect(result).toBe('dQw4w9WgXcQ');
  });

  it('should extract the correct video ID from a standard watch URL containing extra query parameters', () => {
    const url = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=45s&feature=share';
    const result = extractYouTubeId(url);
    expect(result).toBe('dQw4w9WgXcQ');
  });

  it('should extract the correct video ID from a short youtu.be URL', () => {
    const url = 'https://youtu.be/dQw4w9WgXcQ';
    const result = extractYouTubeId(url);
    expect(result).toBe('dQw4w9WgXcQ');
  });

  it('should extract the correct video ID from a short youtu.be URL with trailing query parameters', () => {
    const url = 'https://youtu.be/dQw4w9WgXcQ?t=120';
    const result = extractYouTubeId(url);
    expect(result).toBe('dQw4w9WgXcQ');
  });

  it('should extract the correct video ID from a YouTube embed URL', () => {
    const url = 'https://www.youtube.com/embed/dQw4w9WgXcQ';
    const result = extractYouTubeId(url);
    expect(result).toBe('dQw4w9WgXcQ');
  });

  it('should extract the correct video ID from a YouTube Shorts URL', () => {
    const url = 'https://www.youtube.com/shorts/dQw4w9WgXcQ';
    const result = extractYouTubeId(url);
    expect(result).toBe('dQw4w9WgXcQ');
  });

  it('should return the input unchanged if it is already a clean 11-character video ID', () => {
    const rawId = 'dQw4w9WgXcQ';
    const result = extractYouTubeId(rawId);
    expect(result).toBe('dQw4w9WgXcQ');
  });

  it('should return null when provided a completely non-YouTube URL', () => {
    const url = 'https://vimeo.com/123456789';
    const result = extractYouTubeId(url);
    expect(result).toBeNull();
  });

  it('should return null when provided an empty string or invalid link', () => {
    expect(extractYouTubeId('')).toBeNull();
    expect(extractYouTubeId('invalid-url-string')).toBeNull();
  });
});

describe('Media Utility - ISO 8601 Duration Parsing', () => {
  it('should parse standard minutes and seconds correctly (e.g., PT27M27S)', () => {
    const duration = 'PT27M27S';
    const result = parseISODuration(duration);
    expect(result).toBe(1647); // 27 * 60 + 27
  });

  it('should parse standard hours, minutes, and seconds correctly (e.g., PT1H12M30S)', () => {
    const duration = 'PT1H12M30S';
    const result = parseISODuration(duration);
    expect(result).toBe(4350); // 3600 + 720 + 30
  });

  it('should parse hours-only durations correctly (e.g., PT2H)', () => {
    const duration = 'PT2H';
    const result = parseISODuration(duration);
    expect(result).toBe(7200); // 2 * 3600
  });

  it('should parse minutes-only durations correctly (e.g., PT45M)', () => {
    const duration = 'PT45M';
    const result = parseISODuration(duration);
    expect(result).toBe(2700); // 45 * 60
  });

  it('should parse seconds-only durations correctly (e.g., PT50S)', () => {
    const duration = 'PT50S';
    const result = parseISODuration(duration);
    expect(result).toBe(50);
  });

  it('should parse raw numeric-seconds format generated by Obsidian Web Clipper (e.g., PT1647)', () => {
    const duration = 'PT1647';
    const result = parseISODuration(duration);
    expect(result).toBe(1647);
  });

  it('should handle raw string numbers directly if the clipper strips the prefix (e.g., "1647")', () => {
    const duration = '1647';
    const result = parseISODuration(duration);
    expect(result).toBe(1647);
  });

  it('should return 0 when provided an empty or invalid duration string', () => {
    expect(parseISODuration('')).toBe(0);
    expect(parseISODuration('invalid_duration')).toBe(0);
  });
});

describe('Media Utility - Custom Picture-in-Picture Visibility Check (shouldShowCustomPip)', () => {
  it('should return true when the player is not embedded in an iframe (loaded directly in a tab on our site)', () => {
    // WHY: If the player is loaded directly, we still want the PiP button to be visible so the user
    // can trigger the custom in-page floating player or native browser PiP modes.
    const result = shouldShowCustomPip({
      isEmbedded: false,
      parentOrigin: 'http://localhost:5000',
      currentOrigin: 'http://localhost:5000'
    });
    expect(result).toBe(true);
  });

  it('should return false when the parent window origin is inaccessible or null (cross-origin / sandboxed)', () => {
    // WHY: If the parent origin is null, we either cannot communicate with the parent or it resides on a 
    // different origin that blocks custom message handling. The custom PiP option must be hidden.
    const result = shouldShowCustomPip({
      isEmbedded: true,
      parentOrigin: null,
      currentOrigin: 'http://localhost:5000'
    });
    expect(result).toBe(false);
  });

  it('should return false when the parent window is on a third-party website (cross-origin mismatch)', () => {
    // WHY: If the player is embedded on an external website (e.g. someotherdomain.com), they cannot 
    // participate in our same-origin Swup-based parent container swapping.
    const result = shouldShowCustomPip({
      isEmbedded: true,
      parentOrigin: 'https://someotherdomain.com',
      currentOrigin: 'http://localhost:5000'
    });
    expect(result).toBe(false);
  });

  it('should return true when the player is embedded inside a same-origin parent window (Astro Modular Note)', () => {
    // WHY: This is the exact condition needed for custom PiP. Since the parent is same-origin, 
    // we can securely swap DOM elements and trigger Swup-based seamless page navigation.
    const result = shouldShowCustomPip({
      isEmbedded: true,
      parentOrigin: 'http://localhost:5000',
      currentOrigin: 'http://localhost:5000'
    });
    expect(result).toBe(true);
  });

  it('should return false if origins match but the port is different', () => {
    // WHY: The same-origin policy is strict on protocol, domain, and port. If ports mismatch, 
    // browser security policies will block parent element swapping.
    const result = shouldShowCustomPip({
      isEmbedded: true,
      parentOrigin: 'http://localhost:3000',
      currentOrigin: 'http://localhost:5000'
    });
    expect(result).toBe(false);
  });

  it('should return false if origins match but the protocol is different (http vs https)', () => {
    // WHY: A secure HTTPS page embedding an HTTP player (or vice versa) constitutes a protocol mismatch,
    // which violates strict same-origin rules and blocks secure parent manipulation.
    const result = shouldShowCustomPip({
      isEmbedded: true,
      parentOrigin: 'https://localhost:5000',
      currentOrigin: 'http://localhost:5000'
    });
    expect(result).toBe(false);
  });
});
