import { describe, it, expect } from 'vitest';
import { extractYouTubeId, parseISODuration } from './media';

describe('Media Utility - YouTube ID Extraction', () => {
  it('should extract the correct video ID from a standard YouTube watch URL', () => {
    const url = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ';
    const result = extractYouTubeId(url);
    expect(result).toBe('dQw4w9WgXcQ');
  });

  it('should extract the correct video ID from a standard watch URL containing extra query parameters', () => {
    const url = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ&t=45s&feature=share';
    const result = extractYouTubeId(url);
    expect(result).toBe('dQw4w9WgXcQ');
  });

  it('should extract the correct video ID from a short youtu.be URL', () => {
    const url = 'https://youtu.be/dQw4w9WgXcQ';
    const result = extractYouTubeId(url);
    expect(result).toBe('dQw4w9WgXcQ');
  });

  it('should extract the correct video ID from a short youtu.be URL with trailing query parameters', () => {
    const url = 'https://youtu.be/dQw4w9WgXcQ?t=120';
    const result = extractYouTubeId(url);
    expect(result).toBe('dQw4w9WgXcQ');
  });

  it('should extract the correct video ID from a YouTube embed URL', () => {
    const url = 'https://www.youtube.com/embed/dQw4w9WgXcQ';
    const result = extractYouTubeId(url);
    expect(result).toBe('dQw4w9WgXcQ');
  });

  it('should extract the correct video ID from a YouTube Shorts URL', () => {
    const url = 'https://www.youtube.com/shorts/dQw4w9WgXcQ';
    const result = extractYouTubeId(url);
    expect(result).toBe('dQw4w9WgXcQ');
  });

  it('should return the input unchanged if it is already a clean 11-character video ID', () => {
    const rawId = 'dQw4w9WgXcQ';
    const result = extractYouTubeId(rawId);
    expect(result).toBe('dQw4w9WgXcQ');
  });

  it('should return null when provided a completely non-YouTube URL', () => {
    const url = 'https://vimeo.com/123456789';
    const result = extractYouTubeId(url);
    expect(result).toBeNull();
  });

  it('should return null when provided an empty string or invalid link', () => {
    expect(extractYouTubeId('')).toBeNull();
    expect(extractYouTubeId('invalid-url-string')).toBeNull();
  });
});

describe('Media Utility - ISO 8601 Duration Parsing', () => {
  it('should parse standard minutes and seconds correctly (e.g., PT27M27S)', () => {
    const duration = 'PT27M27S';
    const result = parseISODuration(duration);
    expect(result).toBe(1647); // 27 * 60 + 27
  });

  it('should parse standard hours, minutes, and seconds correctly (e.g., PT1H12M30S)', () => {
    const duration = 'PT1H12M30S';
    const result = parseISODuration(duration);
    expect(result).toBe(4350); // 3600 + 720 + 30
  });

  it('should parse hours-only durations correctly (e.g., PT2H)', () => {
    const duration = 'PT2H';
    const result = parseISODuration(duration);
    expect(result).toBe(7200); // 2 * 3600
  });

  it('should parse minutes-only durations correctly (e.g., PT45M)', () => {
    const duration = 'PT45M';
    const result = parseISODuration(duration);
    expect(result).toBe(2700); // 45 * 60
  });

  it('should parse seconds-only durations correctly (e.g., PT50S)', () => {
    const duration = 'PT50S';
    const result = parseISODuration(duration);
    expect(result).toBe(50);
  });

  it('should parse raw numeric-seconds format generated by Obsidian Web Clipper (e.g., PT1647)', () => {
    const duration = 'PT1647';
    const result = parseISODuration(duration);
    expect(result).toBe(1647);
  });

  it('should handle raw string numbers directly if the clipper strips the prefix (e.g., "1647")', () => {
    const duration = '1647';
    const result = parseISODuration(duration);
    expect(result).toBe(1647);
  });

  it('should return 0 when provided an empty or invalid duration string', () => {
    expect(parseISODuration('')).toBe(0);
    expect(parseISODuration('invalid_duration')).toBe(0);
  });
});
